- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: Dark

- id: 'telegram_piboot'
  alias: 'Telegram o uruchomieniu hassio'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: notify.send
    data:
      message: Home Assistant on Pi booted
      
- id: 'telegram_window'
  alias: 'Telegram o otwartym oknie'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions:
        - condition: template
          value_template: "{{ ( states.sensor.temp201_ogrod_ganek_temperature.state  ) < ( states.sensor.temp005_parter_biuro_temperature.state ) }}"
        - condition: state
          entity_id: group.upstairs_windows
          state: 'on'
  action:
  - service: notify.send
    data:
      message: Okno na piętrze jest otwarte
      
      
- id: 'backup_to_git'
  alias: 'Automatyczne wysłanie kopii zapasowej do GITa'
  trigger:
    - platform: time_pattern
      hours: "2"
  action:
    - service: shell_command.backup