
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list /config/automation/
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/fontawesome/hass-fontawesome-solid.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

lovelace:
  mode: yaml

binary_sensor: !include binary_sensors.yaml

shell_command:
    backup: sh /config/gitupdate.sh

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_user_id

notify:
  - name: sw132y
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id
    
logger:
    default: debug

config:

customizer:
  custom_ui: local

vacuum:
  - platform: mqtt
    name: "MQTT Vacuum"
    schema: state
    supported_features:
      - start
      - pause
      - stop
      - return_home
      - battery
      - status
      - locate
      - clean_spot
      - fan_speed
      - send_command
    command_topic: "vacuum/command"
    state_topic: "vacuum/state"
    set_fan_speed_topic: "vacuum/set_fan_speed"
    fan_speed_list:
      - min
      - medium
      - high
      - max
    send_command_topic: "vacuum/send_command"

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 48
  platform: smart_life

light:
  - platform: group
    name: Chillroom Lights
    entities:
      - light.light201_pietro_chillroom
      - light.light202_pietro_chillroom
