group: !include groups.yaml
automation: !include_dir_merge_list /config/automation/
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/fontawesome/hass-fontawesome-solid.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

lovelace:
  mode: yaml

binary_sensor: !include customize_binary_sensors.yaml
sensor: !include customize_sensors.yaml

shell_command:
    backup: sh /config/gitupdate.sh

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      - !secret telegram_user_id

notify:
  - name: sw132y
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id
    
logger:
    default: debug

config:

customizer:
  custom_ui: local

light:
  - platform: group
    name: Chillroom Lights
    entities:
      - light.light201_pietro_chillroom
      - light.light202_pietro_chillroom