- platform: template
  sensors:
    relay008_energy_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay008_energy_energy_today') | float * 0.55) | round(2) }}"
      icon_template: "mdi-currency-usd"
    relay102_grzejnik_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay102_grzejnik_energy_today') | float * 0.55) | round(2) }}"
      icon_template: "mdi-currency-usd"
      