- platform: template
  sensors:
    relay008_energy_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay008_energy_energy_today') | float * 0.63) | round(2) }}"
      icon_template: mdi:currency-usd
    relay102_grzejnik_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay102_grzejnik_energy_today') | float * 0.63) | round(2) }}"
      icon_template: mdi:currency-usd
    relay003_gniazdko_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay003_gniazdko_energy_today') | float * 0.63) | round(2) }}"
      icon_template: mdi:currency-usd
    relay004_gniazdko_komputer_daily_cost:
      friendly_name: "Current cost"
      unit_of_measurement: 'zł'
      value_template: "{{ (states('sensor.relay004_gniazdko_komputer_energy_today') | float * 0.63) | round(2) }}"
      icon_template: mdi:currency-usd
- platform: mqtt
  name: Particulate Matter Sensor
  state_topic: weather/meteopi
- platform: mqtt
  name: "Meteo PM2.5"
  state_topic: "weather/meteopi"
  value_template: "{{ value_json.pm25 }}"
  json_attributes_topic: "weather/meteopi"
  json_attributes_template: "{{ value_json.pm25 | tojson }}"
- platform: mqtt
  name: "Meteo PM10"
  state_topic: "weather/meteopi"
  value_template: "{{ value_json.pm10 }}"
  json_attributes_topic: "weather/meteopi"
  json_attributes_template: "{{ value_json.pm10 | tojson }}"
- platform: mqtt
  name: "Meteo Temperature"
  state_topic: "weather/meteopi"
  value_template: "{{ value_json.temperature | float | round(1) }}"
  json_attributes_topic: "weather/meteopi"
  json_attributes_template: "{{ value_json.temperature | tojson }}"
- platform: mqtt
  name: "Meteo Pressure"
  state_topic: "weather/meteopi"
  value_template: "{{ value_json.pressure | float | round(1) }}"
  json_attributes_topic: "weather/meteopi"
  json_attributes_template: "{{ value_json.pressure | tojson }}"
- platform: mqtt
  name: "Meteo Humidity"
  state_topic: "weather/meteopi"
  value_template: "{{ value_json.humidity | float | round(0) }}"
  json_attributes_topic: "weather/meteopi"
  json_attributes_template: "{{ value_json.humidity | tojson }}"