title: Sensory
views:
  - badges:
      - sensor.temp005_parter_biuro_temperature
      - sensor.temp005_parter_biuro_humidity
      - sensor.temp101_pietro_sypialnia_temperature
      - sensor.temp008_parter_salon_temperature
      - sensor.temp101_pietro_sypialnia_humidity
      - sensor.temp201_ogrod_ganek_temperature
      - sensor.temp201_ogrod_ganek_humidity
      - sensor.temp201_ogrod_ganek_pressure
      - sun.sun
      - binary_sensor.kontr102_pietro_sypialnia_poludnie_contact
      - binary_sensor.kontr101_pietro_sypialnia_wschod_contact
      - binary_sensor.kontr103_pietro_chillroom_contact
      - binary_sensor.kontr104_pietro_goscinny_contact
      - binary_sensor.kontr106_pietro_lazienka_contact
      - binary_sensor.kontr105_pietro_ignacy_contact
      - binary_sensor.0x00124b0018e32cb8_router
      - binary_sensor.0x00124b0018ed2935_router
    cards:
      - entities:
          - entity: binary_sensor.kontr102_pietro_sypialnia_poludnie_contact
          - entity: binary_sensor.kontr101_pietro_sypialnia_wschod_contact
          - entity: binary_sensor.kontr104_pietro_goscinny_contact
          - entity: binary_sensor.kontr103_pietro_chillroom_contact
          - entity: binary_sensor.kontr106_pietro_lazienka_contact
          - entity: binary_sensor.kontr105_pietro_ignacy_contact
          - entity: group.upstairs_windows
        show_header_toggle: false
        theme: default
        title: Okna
        type: entities
      - entities:
          - entity: sensor.temp008_parter_salon_temperature
          - entity: sensor.temp008_parter_salon_humidity
          - entity: sensor.temp005_parter_biuro_temperature
          - entity: sensor.temp005_parter_biuro_humidity
          - entity: sensor.temp101_pietro_sypialnia_temperature
          - entity: sensor.temp101_pietro_sypialnia_humidity
        show_header_toggle: false
        title: Dom
        type: entities
      - entities:
          - entity: sensor.temp201_ogrod_ganek_temperature
          - entity: sensor.temp201_ogrod_ganek_humidity
          - entity: sensor.temp201_ogrod_ganek_pressure
        show_header_toggle: false
        title: Ogród
        type: entities
      - entity: switch.relay001_parter_wejscie_furtka
        hold_action:
          action: toggle
        icon_height: 32px
        name: Furtka
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: entity-button
      - entity: weather.dom
        type: weather-forecast
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: automation.automatyczne_wyslanie_kopii_zapasowej_do_gita
        hold_action:
          action: none
        icon_height: 25px
        name: Kopia sapasowa GIT
        show_icon: true
        show_name: true
        tap_action:
          action: call-service
          service: shell_command.backup
        type: entity-button
    path: akcje
    theme: dark
    title: Akcje
