title: Dom
resources:
  - url: /local/floorplan/plugins/card-mod.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
views:
  - badges: []
    path: default_view
    title: Home
    cards:
      - !include /config/lovelace/views/parter-wejscie.yaml
      - !include /config/lovelace/views/pietro-okna.yaml
      - !include /config/lovelace/views/pietro-ignacy.yaml
      - !include /config/lovelace/views/parter-salon.yaml
      - !include /config/lovelace/views/pietro-chillroom.yaml
      - !include /config/lovelace/views/pietro-sypialnia.yaml
      - !include /config/lovelace/views/parter-biuro.yaml
      - !include /config/lovelace/views/pomiar-energii.yaml
      - !include /config/lovelace/views/weather.yaml
  - badges: []
    path: admin
    title: Admin
    cards:
      - type: entities
        show_header_toggle: false    
        title: Admin
        entities:
          - type: weblink
            url: http://192.168.1.1
            name: TP-Link router
          - type: weblink
            url: http://192.168.1.104:9541/
            name: Tasmota admin