resources:
  - url: /local/floorplan/plugins/card-mod.js?v=1
    type: js
  - url: /community_plugin/button-card/button-card.js?v=1
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js?v=1
    type: module
views:
  - badges: []
    path: default_view
    title: Pulpit
    cards:
      - !include /config/lovelace/views/01-pulpit.yaml
  - badges: []
    path: ogrzewanie
    title: Ogrzewanie
    cards:
      - !include /config/lovelace/views/05-ogrzewanie.yaml
  - badges: []
    path: pomiar_energii
    title: Pomiar energii
    cards:
      - !include /config/lovelace/views/03-pomiar-energii.yaml
  # - badges: []
  #   path: rozrywka
  #   title: Rozrywka
  #   cards:
  #     - !include /config/lovelace/views/04-rozrywka.yaml
  - badges: []
    path: floorplan
    title: Floorplan
    cards:
      - !include /config/lovelace/views/floorplan/parter.yaml
      - !include /config/lovelace/views/floorplan/pietro.yaml
  - badges: []
    path: ustawienia
    title: Ustawienia
    cards:
      - !include /config/lovelace/views/06-ustawienia.yaml