title: Dom
resources:
  - url: /local/floorplan/plugins/card-mod.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
views:
  - badges: []
    cards:
      - !include /config/lovelace/views/parter-wejscie.yaml
      - !include /config/lovelace/views/pietro-okna.yaml
      - !include /config/lovelace/views/pietro-ignacy.yaml
      - !include /config/lovelace/views/parter-salon.yaml
      - !include /config/lovelace/views/pietro-chillroom.yaml
      - !include /config/lovelace/views/pietro-sypialnia.yaml
      - !include /config/lovelace/views/dom-klimat.yaml
      - !include /config/lovelace/views/weather.yaml
    path: default_view
    title: Home