title: Dom
resources:
  - url: /local/floorplan/plugins/card-mod.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
views:
  - badges: []
    path: default_view
    title: Pulpit
    cards:
      - !include /config/lovelace/views/01-pulpit.yaml
  - badges: []
    path: pietro
    title: Piętro
    cards:
      - !include /config/lovelace/views/02-pietro.yaml
  - badges: []
    path: pomiar_energii
    title: Pomiar energii
    cards:
      - !include /config/lovelace/views/03-pomiar-energii.yaml
  - badges: []
    path: rozrywka
    title: Rozrywka
    cards:
      - !include /config/lovelace/views/04-rozrywka.yaml
      # - type: entities
      #   show_header_toggle: false    
      #   title: Admin
      #   entities:
      #     - type: weblink
      #       url: http://192.168.1.1
      #       name: TP-Link router
      #     - type: weblink
      #       url: http://192.168.1.104:9541/
      #       name: Tasmota admin