- alias: 'Notification sypialnia temperature is below 20 celcius'
  trigger:
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.temp101_pietro_sypialnia_temperature
        below: 19
      - condition: time
        after: '18:00:00'
        before: '08:00:00'
  action:
  - service: notify.sw132y
    data:
      message: Temperatura w sypialni wynosi {{states.sensor.temp101_pietro_sypialnia_temperature.state_with_unit}}

- alias: 'Notification humidity is below 60%'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.temp101_pietro_sypialnia_hummidity
        below: 60
      - condition: time
        after: '18:00:00'
        before: '23:00:00'
  action:
  - service: notify.sw132y
    data:
      message: Wiglotnośc powietrzna w sypialni wynosi {{states.sensor.temp101_pietro_sypialnia_hummidity.state_with_unit}}


- alias: 'Notification window is opened when is cold outside'
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: "/45"
  condition:
    condition: and
    conditions:
        - condition: template
          value_template: "{{ ( states.sensor.temp201_ogrod_ganek_temperature.state  ) < ( states.sensor.temp005_parter_biuro_temperature.state ) }}"
        - condition: state
          entity_id: group.upstairs_windows
          state: 'on'
  action:
  - service: notify.sw132y
    data:
      message: Okno na piętrze jest otwarte


- alias: 'Notification: Outside lights changed state'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.relay002_parter_wejscie_oswietle
    - platform: state
      entity_id: switch.relay005_parter_wejscie_dzwonek
    - platform: state
      entity_id: switch.relay001_parter_wejscie_furtka
  action:
    service: notify.sw132y
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} jest teraz {{trigger.to_state.state}}