- alias: 'Action: Change heating mode to "Poranek"'
  trigger:
    - platform: time
      at: "05:00:00"
  condition:
    condition: state
    entity_id: input_boolean.wakacje
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_poranek
  - service: notify.sw132y
    data:
      message: Tryb grzania "poranek".

- alias: 'Action: Change heating mode to "Dzień"'
  trigger:
    - platform: time
      at: "09:00:00"
  condition:
    condition: state
    entity_id: input_boolean.wakacje
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_dzien
  - service: notify.sw132y
    data:
      message: Tryb grzania "dzień".

- alias: 'Action: Change heating mode to "Wieczór"'
  trigger:
    - platform: time
      at: "17:00:00"
  condition:
    condition: state
    entity_id: input_boolean.wakacje
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_wieczor
  - service: notify.sw132y
    data:
      message: Tryb grzania "wieczór".


- alias: 'Action: Change heating mode to "Noc"'
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    condition: state
    entity_id: input_boolean.wakacje
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_noc
  - service: notify.sw132y
    data:
      message: Tryb grzania "noc".

- alias: 'Action: Change heating mode to "Wakacje"'
  trigger:
    - platform: state
      entity_id: input_boolean.wakacje
      from: 'off'
      to: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_wakacje
  - service: notify.sw132y
    data:
      message: Tryb grzania "wakacje".

- alias: 'Action: Turn off "Wakacje" mode'
  trigger:
    - platform: state
      entity_id: input_boolean.wakacje
      from: 'on'
      to: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.ogrzewanie_dzien
  - service: notify.sw132y
    data:
      message: Wyłączenie trybu grzania "wakacje".