- alias: 'Action: Turn off outdoor lights'
  trigger:
    - platform: time
      at: "23:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.relay002_parter_wejscie_oswietle
        state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.relay002_parter_wejscie_oswietle
  - service: notify.sw132y
    data:
      message: Automatyczne wyłączenie świateł zewnętrznych.