- alias: 'Notification: Temperature is below 20 celcius'
  trigger:
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.temp101_pietro_sypialnia_temperature
        below: 19
      - condition: time
        after: '18:00:00'
        before: '08:00:00'
  action:
  - service: notify.sw132y
    data:
      message: Temperatura w sypialni wynosi {{states.sensor.temp101_pietro_sypialnia_temperature.state_with_unit}}

- alias: 'Notification: Window is open'
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions:
        - condition: state
          entity_id: group.upstairs_windows
          state: 'on'
  action:
  - service: notify.sw132y
    data_template:
      message: |
        {% for state in states.binary_sensor -%}
        {% if state.entity_id.startswith('binary_sensor.kontr') and state.entity_id.endswith('_contact') and state.name.startswith('Okno') %}
        {% if is_state(state.entity_id, 'on') %}
        {{state.name | replace("Okno ", "")}} jest otwarte.
        {%- endif %}
        {%- endif %}
        {%- endfor %}

- alias: 'Notification: Entity has changed state to "on"'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.relay002_parter_wejscie_oswietle
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.relay005_parter_wejscie_dzwonek
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.relay001_parter_wejscie_furtka
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kontr203_ogrod_szopka_contact
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kontr202_ogrod_brama_contact
      from: 'off'
      to: 'on'
      for:
        seconds: 10
  action:
    service: notify.sw132y
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} jest teraz {{trigger.to_state.state}}


- alias: 'Notification: Entity has changed state to "off"'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.relay002_parter_wejscie_oswietle
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.relay005_parter_wejscie_dzwonek
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.kontr202_ogrod_brama_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 10
  action:
    service: notify.sw132y
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} jest teraz {{trigger.to_state.state}}

- alias: 'Notification: Remind to close if is state is still "on"'
  initial_state: 'on'
  trigger:
    - platform: time
      at: "21:00:00"
  condition:
    condition: or
    conditions:
        - condition: state
          entity_id: binary_sensor.kontr202_ogrod_brama_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kontr203_ogrod_szopka_contact
          state: 'on'
  action:
    service: notify.sw132y
    data_template:
      message: |
        {% if is_state('binary_sensor.kontr202_ogrod_brama_contact', 'on') %}Brama nadal jest otwarta. {%- endif %}
        {% if is_state('binary_sensor.kontr203_ogrod_szopka_contact', 'on') %}Szopka nadal jest otwarta. {%- endif %}