- alias: 'Notification: Temperature is below 20 celcius'
  trigger:
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.temp101_pietro_sypialnia_temperature
        below: 19
      - condition: time
        after: '18:00:00'
        before: '08:00:00'
  action:
  - service: notify.sw132y
    data:
      message: Temperatura w sypialni wynosi {{states.sensor.temp101_pietro_sypialnia_temperature.state_with_unit}}

- alias: 'Notification: Window is open when is cold outside'
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions:
        # - condition: template
        #   value_template: "{{ ( states.sensor.temp201_ogrod_ganek_temperature.state  ) < ( states.sensor.temp005_parter_biuro_temperature.state ) }}"
        - condition: state
          entity_id: group.upstairs_windows
          state: 'on'
  action:
  - service: notify.sw132y
    data:
      message: Okno na piętrze jest otwarte


- alias: 'Notification: Entity has changed state to "on"'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.relay002_parter_wejscie_oswietle
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.relay005_parter_wejscie_dzwonek
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.relay001_parter_wejscie_furtka
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kontr202_ogrod_brama_contact
      from: 'off'
      to: 'on'
      for:
        seconds: 10
  action:
    service: notify.sw132y
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} jest teraz {{trigger.to_state.state}}


- alias: 'Notification: Entity has changed state to "off"'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.relay002_parter_wejscie_oswietle
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.relay005_parter_wejscie_dzwonek
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.kontr202_ogrod_brama_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 10
  action:
    service: notify.sw132y
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} jest teraz {{trigger.to_state.state}}

  